version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.11-buster
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y -q --no-install-recommends python3-venv
            python3 -m venv venv
            . venv/bin/activate
            make requirements

      - run:
          name: Run the code quality check
          command: |
            . venv/bin/activate
            make test.quality

      - run:
          name: Run the unit tests
          command: |
            . venv/bin/activate
            make test

      - save_cache:
          key: dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - venv
