name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: '**'

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: make requirements
      - name: Run code quality checks
        run: make test.quality
      - name: Run unit tests
        run: make test
